layout_spectrum: 1
typography_spectrum: 0.7754653
color:
  saturation: 0.296796
  lightness: 0.1070826
  brandStrength: 0.4957841
  brandColors:
    - '#546B13'
    - '#030201'
    - '#FFFFFF'
    - '#A35A0E'
    - '#E9B35D'
  rhythmicContrast: 0.8752108
name: Carl H. Blomqvist
